"""add PR check state tracking columns

Revision ID: 25c4c5b06326
Revises: d5bb9584b2b9
Create Date: 2026-09-30 13:48:36.817652

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '25c4c5b06326'
down_revision: str | None = 'd5bb9584b2b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'pull_requests',
        sa.Column('check_status', sa.String(length=20), nullable=False, server_default='pending'),
    )
    op.add_column('pull_requests', sa.Column('check_conclusion', sa.String(length=20), nullable=True))
    op.add_column('pull_requests', sa.Column('check_summary', sa.String(), nullable=True))
    op.add_column('pull_requests', sa.Column('comment_body', sa.String(), nullable=True))
    op.create_unique_constraint('uq_pull_requests_repository_number', 'pull_requests', ['repository_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pull_requests_repository_number', 'pull_requests', type_='unique')
    op.drop_column('pull_requests', 'comment_body')
    op.drop_column('pull_requests', 'check_summary')
    op.drop_column('pull_requests', 'check_conclusion')
    op.drop_column('pull_requests', 'check_status')
    # ### end Alembic commands ###
