"""add linked_issue_refs and commit uniqueness

Revision ID: d5bb9584b2b9
Revises: e8dbf3152aac
Create Date: 2026-09-27 22:23:56.679908

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd5bb9584b2b9'
down_revision: str | None = 'e8dbf3152aac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('linked_issue_refs', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.create_unique_constraint('uq_commits_repository_sha', 'commits', ['repository_id', 'sha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_commits_repository_sha', 'commits', type_='unique')
    op.drop_column('commits', 'linked_issue_refs')
    # ### end Alembic commands ###
