"""add line_risk_top_n to repositories

Revision ID: fae879913708
Revises: 25c4c5b06326
Create Date: 2026-09-30 16:51:19.265639

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fae879913708'
down_revision: str | None = '25c4c5b06326'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'repositories',
        sa.Column('line_risk_top_n', sa.Integer(), nullable=False, server_default='5'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'line_risk_top_n')
    # ### end Alembic commands ###
